version: "3.8"

services:
  # 🐬 Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: scninja-db
    restart: always
    environment:
      MYSQL_DATABASE: naruto
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - appnet

  # ⚙️ Backend (Spring Boot)
  backend:
    build: .
    container_name: scninja-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/naruto?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpwd
      SERVER_PORT: 8080
    networks:
      - appnet

  # 🌐 Frontend (React + Nginx)
  frontend:
    build: ./frontend
    container_name: scninja-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - appnet

# Volumen para persistir datos MySQL
volumes:
  dbdata:

# Red común para comunicación interna entre servicios
networks:
  appnet:
    driver: bridge
